spring:
 application:
  name: spring-aot-benchmark
 threads:
   virtual:
    enabled: false
server:
 port: 8080
logging:
 level:
  root: ${LOG_LEVEL_ROOT:INFO}
  com.popovrnd.springaotbenchmark: ${LOG_LEVEL_BENCHMARK:WARN}