spring:
  application:
    name: spring-benchmark
  threads:
    virtual:
      enabled: ${VT_ENABLED:false}
server:
  port: 8080
  tomcat:
    accept-count: ${ACCEPT_COUNT:100}
    max-connections: ${MAX_CONNECTIONS:8192}
    threads:
      max: ${GLOBAL_CONCURRENCY:200}
      max-queue-capacity: ${MAX_QUEUE_SIZE:1}

concurrency:
  locals:
    path1: ${PATH1_CONCURRENCY:100}
    path2: ${PATH2_CONCURRENCY:80}
    path3: ${PATH3_CONCURRENCY:20}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

logging:
  level:
    root: ${LOG_LEVEL_ROOT:INFO}
    com.popovrnd.springbenchmark: ${LOG_LEVEL_BENCHMARK:WARN}