spring:
  application:
    name: spring-benchmark
  threads:
    virtual:
      enabled: ${VT_ENABLED:true}
server:
  port: 8080
  tomcat:
    threads:
      max: ${MAX_THREADS:200}
    max-connections: ${TOMCAT_MAX_CONNECTIONS:8192}

concurrency:
  max: ${MAX_CONCURRENCY:-1}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

logging:
  level:
    root: ${LOG_LEVEL_ROOT:INFO}
    com.popovrnd.springaotbenchmark: ${LOG_LEVEL_BENCHMARK:WARN}